manager/urls.py
from django.conf.urls import url
from manager import views

app_name = 'manager'

urlpatterns = [

    url(r'^dashboard/$', views.DashboardCBV.as_view(), name="dashboard"),
    url(r'^search/$', views.SearchCBV.as_view(), name="search"),
    url(r'^pickups/$', views.PickupCBV.as_view(), name="pickups"),
    url(r'^approve/(?P<pk>\d+)/$', views.ApproveCBV.as_view(), name="approve"),
    url(r'^approve/(?P<pk>\d+)/location/(?P<location_id>\d+)/$', views.ApproveCBV.as_view(), name="approve"),
    url(r'^dispatch/(?P<pk>\d+)/$', views.DispatchCBV.as_view(), name="dispatch"),
    url(r'^about/$', views.AboutCBV.as_view(), name="about"),

]

recom/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from recom.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^user/', include("user.urls", namespace="user")),
    url(r'^manager/', include("manager.urls", namespace="manager")),
]

user/urls.py
from django.conf.urls import url
from user import views 

app_name = 'user'

urlpatterns = [

    url(r'^dashboard/$', views.DashboardCBV.as_view(), name="dashboard"),
    url(r'^search/$', views.SearchCBV.as_view(), name="search"),
    url(r'^records/$', views.RecordsCBV.as_view(), name="records"),
    url(r'^pickups/(?P<pk>\d+)/$', views.PickupCBV.as_view(), name="pickups"),
    url(r'^retrieve/(?P<pk>\d+)/$', views.RetrieveCBV.as_view(), name="retrieve"),
    url(r'^about/$', views.AboutCBV.as_view(), name="about"),

]

manager/models.py
from django.db import models

class LocationBarcode(models.Model):
    barcode = models.CharField(max_length=255)

    def __str__(self):
        return self.barcode
    
    class Meta: 
        verbose_name = "Location Barcode"
        verbose_name_plural = "Location Barcodes"

manager/forms.py
from django import forms 
from user.models import Record, RecordStatus


class RecordForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(RecordForm, self).__init__(*args, **kwargs)
        # self.initial['status'] = RecordStatus.objects.get(id=self.initial['status']).status

    class Meta():
        model = Record
        fields = ["barcode", "reference", "description", "dept", "status"]
        widgets = {
            'barcode': forms.TextInput(attrs={'class': 'form-control'}),
            'reference': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'dept': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'})
        }

manager/views.py

from django.views.generic import TemplateView, CreateView, ListView, View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from django.shortcuts import redirect

from manager.forms import RecordForm
from manager.models import LocationBarcode

from user.models import Record, Department, RecordStatus


class DashboardCBV(TemplateView):
    template_name = 'manager/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardCBV, self).get_context_data(**kwargs)

        context['records'] = Record.objects.count()
        context['joining'] = "00"
        context['title'] = "Dashboard"

        return context


class SearchCBV(ListView):
    template_name = 'manager/search.html'
    model = Record
    context_object_name = "records"

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(SearchCBV, self).get_context_data(**kwargs)

        context["departments"] = Department.objects.all()
        context["recordStatus"] = RecordStatus.objects.all()
        context['title'] = "Search"

        return context

    def get_queryset(self):
        # records = Record.objects.filter(status=3)
        records = Record.objects.all()
        
        barcode = self.request.GET.get("barcode", '')
        reference = self.request.GET.get("reference", '')
        dept = self.request.GET.get("dept", 'none')
        status = self.request.GET.get("status", 'none')

        if barcode != "":
            records = records.filter(barcode__iexact = barcode.strip())

        if reference != "":
            records = records.filter(reference__iexact=reference.strip())

        if dept != "none":
            records = records.filter(dept=dept.strip())

        if status != "none":
            records = records.filter(status=status.strip())

        return records


class PickupCBV(ListView):
    template_name = 'manager/pickup.html'
    model = Record
    context_object_name = "records"
    queryset = Record.objects.filter(status__in=[1,3])

    def get_context_data(self, **kwargs):
        context = super(PickupCBV, self).get_context_data(**kwargs)
        context['title'] = "Pickups"
        context['locations'] = LocationBarcode.objects.all()
        return context


class ApproveCBV(View):

    def get(self, *args, **kwargs):
        record_id = kwargs["pk"]
        location_id = kwargs["location_id"]
        status = RecordStatus.objects.get(id=2)
        location = LocationBarcode.objects.get(id=location_id)
        record = Record.objects.get(pk=record_id)
        record.status = status
        record.location = location
        record.save()

        return redirect("manager:search")


class DispatchCBV(View):

    def get(self, *args, **kwargs):
        id = kwargs["pk"]

        record = Record.objects.get(pk=id)
        record.status = RecordStatus.objects.get(id=4)
        record.location = None
        record.save()

        return redirect("manager:search")


class AboutCBV(TemplateView):
    template_name = 'manager/about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutCBV, self).get_context_data(**kwargs)
        context['title'] = "About"
        return context

templates/manager/about.html
{% extends 'manager/base.html' %}

{% load static %}

{% block main %}
<main class="main-section">

    <h1 class="page-heading">About</h1>

    <p> 
        IKONRecoM is a unique and robust Software Solution to help you manage your Hard copy Records and Documents in the most
        effective and professional manner to meet the challenges of Compliance, Risk Management & Business Continuity, while
        facilitating a Secure environment with access Audit Trails for your critical information.
    </p>

    <p>
        IKONRecoM is a Web based application suitable for any organization which is considering to efficiently manage its
        physical business documents. It enables customers to Control, Regulate, Archive, Retrieve, Store and Destroy the
        physical business documents effectively and efficiently, ensuring availability of Records on Demand, every-time. Fully
        featured system for In-house management and bulk processing of Physical Documents.
    </p>

</main>
{% endblock %}

templates/manager/base.html

{% load static %}

<link rel="stylesheet" href="{% static 'css/grid24-bootstrap.css' %}">
<script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
<script src='{% static "js/bootstrap.bundle.min.js" %}'></script>

<style>



    body {
        padding-left: 3em; 
        padding-right: 3em; 
        background-color: #202020;
    }

    header {
        /* padding-left: 2em;  */
    }

    .ikon-dark-blue {
        color: #064D81;
    }

    .ikon-light-blue {
        color: #00B0F0;
    }

    .ikon-parrot {
        color: #A6CE39
    }

    .section {
        background-color: #fff;
        border-radius: 10px;
        margin-top: 0.5em;
        padding-left: 0.7em;
        padding-top: 0.1em;
        padding-bottom: 0.2em;
    }

    .main-section {
        background-color: #fff;
        border-radius: 10px;
        padding-left: 2em;
        padding-right: 2em;
        padding-top: 0.8em;
        padding-bottom: 2em;

    }

    footer {
        background-color: #fff;
        border-radius: 10px;
        padding-left: 2em;
        padding-right: 1em;
        padding-top: 0.8em;
        padding-bottom: 0.8em;
        margin-top: 1em;
        margin-bottom: 1em;
        color: #064D81;
    }

    h1.page-heading {
        color: #064D81;
        font-size: 2em;
        border-bottom: 2px solid #064D81;
        /* margin-left: 1em; */
        /* margin-right: 1em; */
    }


    .navbar-expand-md .navbar-nav .nav-link {
        padding: 0;
    }

    ul.user {
        margin-right: 0.8em;
        color: #064D81;
        font-weight: 600;
        font-size: 1.2em;
    }

    ul.user li{
        list-style: none;
    }

    ul li.nav-item {
        margin-right: 2em;
    }

    ul li.active {
        border-bottom: 2px solid #A6CE39;
    }

    .navbar-nav .active > .nav-link {
        color: #064D81 !important;
    }

    span.logout {
        font-size: 0.5em !important;
        margin-right: 1.5em;
        margin-top: 0.6em;
    }

    nav.navbar {
        background-color: white;
        border-radius: 10px;
        margin-top: 1em;
        margin-bottom: 1em;
        padding-top: 0.7em;
        padding-bottom: 0.7em;
        padding-left: 2em;
    }

    .remove_underline{
        text-decoration: None !important;
    }
</style>

{% block style %}
{% endblock %}


<header>
    
    <h1 class="section"> 
        <a class="remove_underline" href="{% url 'index' %}"> 
            <span class="ikon-dark-blue">IKON</span><span class="ikon-parrot">RecoM</span> 
        </a>
        <span class="logout float-right">
            <a class="" href="{% url 'index' %}">Logout</a>
        </span>
    </h1>

    <nav class="navbar navbar-expand-md navbar-light lightbg">

        <ul class="navbar-nav mr-auto ">
            <li class="nav-item {% if title == 'Dashboard' %} {{ 'active' }} {% endif %}">
                <a class="nav-link" href="{% url 'manager:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item {% if title == 'Search' %} {{ 'active' }} {% endif %}">
                <a class="nav-link" href="{% url 'manager:search' %}">Search</a>
            </li>
            <li class="nav-item {% if title == 'Pickups' %} {{ 'active' }} {% endif %}">
                <a class="nav-link" href="{% url 'manager:pickups' %}">Pickups</a>
            </li>
            <li class="nav-item {% if title == 'About' %} {{ 'active' }} {% endif %}">
                <a class="nav-link" href="{% url 'manager:about' %}">About</a>
            </li>
        </ul>

        <ul class="navbar-nav user">
            <li>Welcome Manager</li>
        </ul>
    </nav>

</header>



{% block main %}
{% endblock %}


<footer>

    &copy; 2019 IKON BPS Pvt Ltd. All Rights Reserved.

</footer>

templates/manager/dashboard.html
{% extends 'manager/base.html' %}

{% load static %}

{% block style %}
<style>
    div.widget {
        border: 2px solid #064D81;
        border-radius: 10px;
        margin-top: 1em;
        margin-bottom: 1em;
        padding: 1em 0.5em;
    }

    h2.widget-heading {
        font-size: 1.5em;
    }

</style>
{% endblock %}

{% block main %}
    <main class="main-section">

        <h1 class="page-heading">Dashboard</h1>
        
        <div class="row">
            
            <div class="col-6">
                <div class="widget">
                    
                    <div class="text-center">
                        <h2> {{ records}} </h2>
                        <h2 class="widget-heading"> Total Records </h2>
                    </div>
                    
                </div>
            </div>
            
            <div class="col-6">
                <div class="widget">
                    
                    <div class="text-center">
                        <h2> 000 </h2>
                        <h2 class="widget-heading"> Pickups Requests </h2>
                    </div>
                    
                </div>
            </div>
            
        </div>

    </main>

{% endblock %}
        
        

templates/manager/pickup.html

{% extends 'manager/base.html' %}

{% load static %}

{% block main %}
<main class="main-section">

    <h1 class="page-heading">Pickup</h1>

<section>
    <table class="table table-striped table-hover">
        <thead>
            <th> ID </th>
            <th> Barcode </th>
            <th> Reference </th>
            <th> Box Barcode </th>
            <th> Location Barcode </th>
            <th> Department </th>
            <th> Status </th>
            <th> Actions </th>
        </thead>

        <tbody>


            {% if records.count != 0 %}
            {% for record in records %}
            <tr>

                <td> {{ record.id }} </td>
                <td> {{ record.barcode }} </td>
                <td> {{ record.reference }} </td>
                <td> {{ record.box_barcode }} </td>
                <td> {{ record.location }} </td>
                <td> {{ record.dept }} </td>
                <td> {{ record.status }} </td>
                <td>

                {% if record.status.status == "Pick Up Requested to Warehouse" %}
                    <a href="{% url 'manager:approve' record.id %}" class="btn btn-info approve">
                        {{ "Approve" }}
                    </a>
                    {% elif record.status.status == "Retrieval Requested to Warehouse" %}
                    <a href="{% url 'manager:dispatch' record.id %}" class="btn btn-info">
                        {{ "Dispatch" }}
                    </a>
                    {% else %}
                    <a href="#" class="btn btn-info"> {{ "Details" }} </a>
                    {% endif %}


                    <a href="#" class="btn btn-secondary">Edit</a>
                    <a href="#" class="btn btn-danger">Delete</a>

                </td>

            </tr>
            {% endfor %}

            {% else %}
            <tr>
                <td colspan=8 class="text-center"> No results found</td>
            </tr>
            {% endif %}


        </tbody>
    </table>
</section>

<section>

    <!-- Modal -->
    <div id="approve" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Select a Location</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <h6> Please select a location for the record </h6>
                    <!-- <select id="location_barcode" name="location" class="form-control"> -->
                    <select id="location_barcode" name="location" class="form-control" >
                        {% for location in locations %}
                            <option value="{{location.id}}"> {{ location }} </option>
                        {% endfor %}
                    </select>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal"> Approve </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"> Close </button>
                </div>
            </div>

        </div>
    </div>
</section>

</main>

<script>
    
    $(document).ready(function () {
        var search_url = "http://127.0.0.1:8000/manager/search/"
        var approve_url = undefined;

        $(".approve").click(function (e) {
            e.preventDefault();
     
            approve_url = e.target.href;
            $('#approve').modal('show');
        });
        
        $('#approve').on('hidden.bs.modal', function (e) {
            
            var location = $("#location_barcode option:selected").val();
            approve_url = approve_url + "location/" + location;
            
            console.log(approve_url);
            
            $.get(approve_url);

            $(window).attr("location", search_url);

            approve_url = undefined;
            
        })
 
    });

</script>

{% endblock %}

templates/manager/records.html
{% extends 'manager/base.html' %}

{% load static %}

{% block style %}
<style>
    label {
        width: 10%;
    }

    input, textarea, select {
        width: 100%;
    }

    input[type=submit] {
        margin-top: 1em;
        width: 30%;
    }

    div.row {
        margin-top: 1em;
    }
</style>
{% endblock %}

{% block main %}
<main class="main-section">

    <h1 class="page-heading">Records</h1>

    <form action="" method="POST" novalidate>

        {% csrf_token %}
   
        <div>
            {{ form.non_field_errors }}
        </div>

        <div class="row">
            <div class="col-3">
                {{ form.barcode.label }}
            </div>
            <div class="col-8">
                <div>
                    {{ form.barcode.errors.as_text }}
                </div>
                <div>
                    {{ form.barcode }}
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-3">
                {{ form.reference.label }}
            </div>
            <div class="col-8">
                <div>
                    {{ form.reference.errors.as_text }}
                </div>
                <div>
                    {{ form.reference }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                {{ form.description.label }}
            </div>
            <div class="col-8">
                <div>
                    {{ form.description.errors.as_text }}
                </div>
                <div>
                    {{ form.description }}
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-3">
                {{ form.dept.label }}
            </div>
            <div class="col-8">
                <div>
                    {{ form.dept.errors.as_text }}
                </div>

                <div>
                    {{ form.dept }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                {{ form.status.label }}
            </div>
            <div class="col-8">
                <div>
                    {{ form.status.errors.as_text }}
                </div>

                <div>
                    {{ form.status }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-9">
                <div class="text-right">
                    <input type="submit" value="Create" class="btn btn-primary">
                </div>
            </div>
        </div>
    </form>

</main>
{% endblock %}

templates/manager/search.html
{% extends 'manager/base.html' %}

{% load static %}
{% load filters %}

{% block style %}

<style>
    .table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
        background-color: #064D81;
        color: white ;
    }

    .section-heading {
        border-bottom: 2px solid #064D81;
        color: #064D81;
    }

    input {
        width: 100%;
    }

    .btn-ikon {
        position: relative;
        background-color: #00B0F0;
        border: 1px solid #00B0F0;
        color: white;
    }

    .btn-ikon:hover {
        background-color: #A6CE39;
        border-color: #A6CE39;
        color: #064D81;
    }

    section.search {
        margin-bottom: 2em;
    }
</style>
{% endblock %}

{% block main %}
<main class="main-section">

    <section class="search">
        <h1 class="page-heading">Search</h1>

        <form action="{% url 'manager:search' %}">


            <div class="row">
                <div class="col-8">
                    <div class="form-group">
                        <label for="barcode">Barcode</label>
                        <input type="text" class="form-control" name="barcode"
                        value="{% if request.GET.barcode %} {{ request.GET.barcode }} {% endif %}">
                    </div>
                </div>
                <div class="col-8">
                    <div class="form-group">
                        <label for="reference">Reference</label>
                        <input type="text" class="form-control" name="reference"
                            value="{% if request.GET.reference %} {{ request.GET.reference }} {% endif %}">
                    </div>
                </div>
                <div class="col-8">
                    <div class="form-group">

                        <label for="status">Status</label>
                        <select class="form-control" id="sel1" name="status">
                            <option value="none"> Select Status </option>

                            {% for status in recordStatus %}
                                <option value="{{status.id}}"
                                    {% if request.GET.status == status.id|slugify %}
                                        {{ 'Selected' }}
                                    {% endif %}
                                > 
                                    {{ status }} 
                                </option>
                            {% endfor %}

                        </select>

                    </div>
                </div>
                <div class="col-24">
                    <div class="row">

                        <div class="offset-16 col-8">
                            <div class="form-group">
                                <input type="submit" class="btn btn-ikon" value="Search">
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </form>
    </section>

    <section>

<h1> 
    {% if request.GET.dept == '2' %}
        {{ "True" }}
    {% endif %}

</h1>
    </section>
    <section>
        <h3 class="section-heading">All Records</h3>
        <table class="table table-striped table-hover">
            <thead>
                <th> ID </th>
                <th> Barcode </th>
                <th> Reference </th>
                <th> Box Barcode </th>
                <th> Location Barcode </th>
                <th> Status </th>
                <th> Actions </th>
            </thead>

            <tbody>


            {% if records.count != 0 %}
                {% for record in records %}
                    <tr>
                    
                        <td> {{ record.id }} </td>
                        <td> {{ record.barcode }} </td>
                        <td> {{ record.reference }} </td>
                        <td> {{ record.box_barcode }} </td>
                        <td> {{ record.location }} </td>
                        <td> {{ record.status }} </td>
                        <td> 
                            <a href="#" class="btn btn-info">
    
                                {% if record.status.status == "Ready for Warehouse" %}
                                    {{ "Pick Up" }}
                                {% elif record.status.status == "Picked Up By Warehouse" %}
                                    {{ "Retrieve" }}
                                {% elif record.status.status == "Ready for Client" %}
                                    {{ "Notify" }}
                                {% elif record.status.status == "Picked Up By Client" %}
                                    {{ "Wait" }}
                                {% else %}
                                    {{ "Details" }}
                                {% endif %}

                            </a>

                            <a href="#" class="btn btn-secondary">Edit</a>
                            <a href="#" class="btn btn-danger">Delete</a>

                        </td>
                    
                    </tr>
                {% endfor %}
            
            {% else %}
            <tr>
                <td colspan=8 class="text-center"> No results found</td>
            </tr>
            {% endif %}

                
            </tbody>
        </table>
    </section>
</main>
{% endblock %}